config/routes.rb
Rails.application.routes.draw do
  get 'pets/index'
  get 'pets/show'
  get 'pets/new'
  get 'pets/edit'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # create pets resource RESTful urls
  resources :pets

  # set root route
  root 'pets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
    validates :name, presence: true
    validates :description, length: {minimum: 10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[ :id])
  end

  def new
    @pet = Pet.new
  end
 
  def create
    @pet = Pet.new(params.require( :pet).permit( :name, :age, :description))
    if @pet.save
      redirect_to @pet
    else 
      render 'new'
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update(params.require( :pet).permit( :name, :age, :description))
    redirect_to @pet
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
  
    redirect_to pets_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/edit.html.erb
<h1>Edit Pet</h1>

<%= form_with model: @pet, local: true do |form| %>
    <p>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
    </p>

    <p>
        <%= form.label :age %><br>
        <%= form.text_area :age %>
    </p>

    <p>
        <%= form.label :description %><br>
        <%= form.text_area :description %>
    </p>

    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/pets/index.html.erb
<table>
  <tr>
    <th colspan="5"></th>
  </tr>
  <% @pets.each do |p| %>
    <tr>
        <td><%= link_to p.name, pet_path(p)  %></td>
        <td><%= link_to 'Edit', edit_pet_path(p) %></td>
        <td><%= link_to 'Remove', pet_path(p), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'New pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= form_with scope: :pet, url: pets_path, data: { turbo: false }, local: true do |form| %>

    <% if @pet.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@pet.errors.count, "error") %> prohibited this article from being saved:
            </h2>
            <ul>
                <% @pet.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :age %><br>
    <%= form.text_area :age %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/pets/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @pet.age %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pet.description %>
</p>

<%= link_to 'Remove', @pet, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Edit', edit_pet_path %>

<%= link_to 'Home', pets_path %>